const KEY='maison5050_simple_v1';
const THEME_KEY='maison5050_theme';
const people=['Guillaume','Claire'];
const categories=['Salle de bains','Cuisine','Électricité','Plomberie','Peinture','Sol','Extérieur','Outillage','Mobilier / déco','Autre'];
const emojis=['🏠','🛁','🍽️','⚡','🚿','🎨','🪵','🌿','🛠️','🪑','🧾','🚚','💡','📦','✨'];
let state=load();
let currentDocFolder=null;
let docSearch='';
let view='home';
let editingId=null;
let editingReimbursementId=null;
let editingProjectId=null;
function applyTheme(){const t=localStorage.getItem(THEME_KEY)||'dark';document.documentElement.dataset.theme=t;const b=document.getElementById('themeToggle');if(b)b.textContent=t==='dark'?'☀️ Clair':'🌙 Sombre'}
function toggleTheme(){const next=(document.documentElement.dataset.theme==='dark')?'light':'dark';localStorage.setItem(THEME_KEY,next);applyTheme()}
applyTheme();
function load(){try{const data=JSON.parse(localStorage.getItem(KEY))||{}; return {expenses:data.expenses||[], reimbursements:data.reimbursements||[], projects:data.projects||[], docFolders:data.docFolders||[{id:'general',name:'Général'}], documents:data.documents||[]}}catch(e){return{expenses:[],reimbursements:[],projects:[],docFolders:[{id:'general',name:'Général'}],documents:[]}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state)); if(cloudSession) cloudSave().catch(e=>console.error('Sync:',e))}
function money(n){return new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(Number(n||0))}
function uid(){return Math.random().toString(36).slice(2)+Date.now().toString(36)}
function v(id){return document.getElementById(id)?.value||''}
function num(id){return parseFloat(String(v(id)).replace(',','.'))||0}
function esc(x){return String(x??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function total(){return state.expenses.reduce((s,e)=>s+Number(e.amount||0),0)}
function projectsTotal(){return state.projects.reduce((s,p)=>s+Number(p.amount||0),0)}
function paidBy(name){return state.expenses.filter(e=>e.payer===name).reduce((s,e)=>s+Number(e.amount||0),0)}
function sentBy(name){return state.reimbursements.filter(r=>r.from===name).reduce((s,r)=>s+Number(r.amount||0),0)}
function receivedBy(name){return state.reimbursements.filter(r=>r.to===name).reduce((s,r)=>s+Number(r.amount||0),0)}
function netPaid(name){return paidBy(name)+sentBy(name)-receivedBy(name)}
function paidOut(name){return paidBy(name)+sentBy(name)}
function other(name){return name==='Guillaume'?'Claire':'Guillaume'}
function balance(){const t=total()/2; const g=netPaid('Guillaume')-t; const c=netPaid('Claire')-t; return {t,g,c}}
function settleText(){const b=balance(); if(Math.abs(b.g)<0.005)return 'Vous êtes à l’équilibre.'; return b.g>0?`Claire doit ${money(b.g)} à Guillaume.`:`Guillaume doit ${money(-b.g)} à Claire.`}
function show(x){view=x;editingId=null;editingReimbursementId=null;editingProjectId=null;render()}
function toast(t){const el=document.getElementById('toast'); el.textContent=t; el.className='show'; setTimeout(()=>el.className='',1600)}
function render(){applyTheme();document.querySelectorAll('.bottom button,.topnav button').forEach(b=>b.classList.remove('active')); document.getElementById('nav-'+view)?.classList.add('active'); document.getElementById('topnav-'+view)?.classList.add('active'); document.getElementById('topnav-'+view)?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'}); if(view==='add')addView(); else if(view==='reimburse')reimburseView(); else if(view==='history')historyView(); else if(view==='projects')projectsView(); else if(view==='documents')documentsView(); else homeView()}
function layout(html){document.getElementById('root').innerHTML=html}
function homeView(){
  const b=balance();
  const gNet=netPaid('Guillaume'), cNet=netPaid('Claire');
  const gPaid=paidOut('Guillaume'), cPaid=paidOut('Claire');
  const gReimb=sentBy('Guillaume'), cReimb=sentBy('Claire');
  const gClass=gNet>cNet?'positive':gNet<cNet?'negative':'';
  const cClass=cNet>gNet?'positive':cNet<gNet?'negative':'';
  const lines=combinedLinesChronological();
  layout(`<div class="grid"><section class="card hero"><span class="pill">Suivi simplifié</span><h2>Qui a payé quoi ?</h2><p class="muted">Chaque dépense est divisée par deux. Les remboursements entre vous réduisent le solde final, sans être ajoutés au total des dépenses.</p><div class="actions"><button onclick="show('add')">+ Ajouter une dépense</button><button class="secondary" onclick="show('reimburse')">Remboursement</button><button class="secondary" onclick="show('projects')">Projets</button><button class="secondary" onclick="show('documents')">Documents</button><button class="secondary" onclick="show('history')">Voir l’historique</button></div></section><div class="card metric total-top"><div class="label">Total dépenses</div><div class="value">${money(total())}</div><div class="submetric">hors remboursements</div></div><div class="card metric halfmetric"><div class="label">Guillaume a payé</div><div class="value ${gClass}">${money(gPaid)}</div><div class="submetric">dont ${money(gReimb)} de remboursement à Claire</div></div><div class="card metric halfmetric"><div class="label">Claire a payé</div><div class="value ${cClass}">${money(cPaid)}</div><div class="submetric">dont ${money(cReimb)} de remboursement à Guillaume</div></div><div class="card metric project-card-home" onclick="show('projects')"><div class="label">Projets</div><div class="value">${state.projects.length}</div><div class="submetric">à venir · ${money(projectsTotal())}</div></div><div class="card metric documents-card-home" onclick="show('documents')"><div class="label">Documents</div><div class="value">${state.documents.length}</div><div class="submetric">factures, devis, photos…</div></div><section class="card full solde-card"><h3>Solde final</h3><div class="settle ${b.g>0?'positive':b.g<0?'negative':''}">${settleText()}</div><p class="muted">Calcul basé sur les dépenses maison divisées en deux, puis corrigé avec les remboursements déjà enregistrés.</p><div class="mini-recap"><span>Remboursements Guillaume → Claire : <b>${money(gReimb)}</b></span><span>Claire → Guillaume : <b>${money(cReimb)}</b></span></div></section><section class="card full"><h3>Détail par dépense</h3><p class="muted">Dépenses et remboursements classés par date. Chaque dépense affiche la part de chacun et la phrase de remboursement associée.</p><div class="list">${lines.map(line=>line.kind==='expense'?expenseLine(line.data):reimbursementLine(line.data)).join('')||'<p class="muted">Aucune dépense. Ajoute la première.</p>'}</div></section></div>`)
}
function combinedLinesChronological(){
  const exp=state.expenses.map(e=>({kind:'expense',date:e.date||'',created:e.id||'',data:e}));
  const reimb=state.reimbursements.map(r=>({kind:'reimbursement',date:r.date||'',created:r.id||'',data:r}));
  return exp.concat(reimb).sort((a,b)=>(b.date||'').localeCompare(a.date||'') || String(b.created).localeCompare(String(a.created)));
}
function expenseLine(e){const half=Number(e.amount||0)/2; const phrase=e.payer==='Guillaume'?`Claire doit ${money(half)} à Guillaume`:`Guillaume doit ${money(half)} à Claire`; const emo=e.emoji||emojiFor(e.category); return `<div class="item"><div class="expense-main"><div class="expense-emoji">${esc(emo)}</div><div><b>${esc(e.title||e.category)}</b><span>${esc(e.date)} · ${esc(e.category)} · payé par ${esc(e.payer)}<br>Montant : ${money(e.amount)} · Part Guillaume : ${money(half)} · Part Claire : ${money(half)}<br><strong class="redline">${phrase}</strong></span></div></div><div class="rowactions"><div class="amount">${money(e.amount)}</div><button class="small secondary" onclick="edit('${e.id}')">Modifier</button><button class="small danger" onclick="del('${e.id}')">Supprimer</button></div></div>`}
function emojiFor(category){const map={'Salle de bains':'🛁','Cuisine':'🍽️','Électricité':'⚡','Plomberie':'🚿','Peinture':'🎨','Sol':'🪵','Extérieur':'🌿','Outillage':'🛠️','Mobilier / déco':'🪑','Autre':'🧾'};return map[category]||'🏠'}
function addView(){const e=editingId?state.expenses.find(x=>x.id===editingId):null; layout(`<div class="card"><h2>${e?'Modifier':'Ajouter'} une dépense</h2><p class="muted">Une seule règle : tu saisis le montant payé et qui a payé. Le partage 50/50 est calculé automatiquement.</p><div class="formgrid"><div class="field"><label>Date</label><input id="date" type="date" value="${esc(e?.date||new Date().toISOString().slice(0,10))}"></div><div class="field"><label>Catégorie</label><select id="category">${categories.map(c=>`<option ${e?.category===c?'selected':''}>${c}</option>`).join('')}</select></div><div class="field"><label>Emoji repère visuel</label><select id="emoji">${emojis.map(em=>`<option ${((e?.emoji)||emojiFor(e?.category))===em?'selected':''}>${em}</option>`).join('')}</select></div><div class="field"><label>Libellé</label><input id="title" placeholder="Ex : Carrelage salle de bains" value="${esc(e?.title||'')}"></div><div class="field"><label>Montant payé</label><input id="amount" type="number" step="0.01" placeholder="0,00" value="${e?Number(e.amount||0):''}"></div><div class="field"><label>Payé par</label><select id="payer">${people.map(p=>`<option ${e?.payer===p?'selected':''}>${p}</option>`).join('')}</select></div><div class="field"><label>Note facultative</label><input id="note" placeholder="Magasin, facture, commentaire..." value="${esc(e?.note||'')}"></div></div><div class="summaryline" id="preview">La moitié sera calculée automatiquement.</div><div class="actions"><button onclick="saveExpense()">${e?'Enregistrer les modifications':'Ajouter la dépense'}</button>${e?'<button class="secondary" onclick="show(\'history\')">Annuler</button>':''}</div></div>`); ['amount','payer'].forEach(id=>document.getElementById(id).addEventListener('input',preview)); document.getElementById('category').addEventListener('change',()=>{if(!editingId)document.getElementById('emoji').value=emojiFor(v('category'));preview()}); preview()}
function preview(){const amount=num('amount'), payer=v('payer'); const half=amount/2; const other=payer==='Guillaume'?'Claire':'Guillaume'; document.getElementById('preview').innerHTML= amount?`Part chacun : <b>${money(half)}</b>. ${other} doit <b>${money(half)}</b> à ${payer}.`:'La moitié sera calculée automatiquement.'}
function saveExpense(){const amount=num('amount'); if(!amount){toast('Entre un montant');return} const data={date:v('date'),category:v('category'),title:v('title')||v('category'),emoji:v('emoji')||emojiFor(v('category')),amount,payer:v('payer'),note:v('note')}; if(editingId){Object.assign(state.expenses.find(e=>e.id===editingId),data); toast('Dépense modifiée')} else {state.expenses.push({id:uid(),...data}); toast('Dépense ajoutée')} save(); show('home')}
function reimburseView(){const r=editingReimbursementId?state.reimbursements.find(x=>x.id===editingReimbursementId):null;layout(`<div class="card"><h2>${r?'Modifier':'Ajouter'} un remboursement</h2><p class="muted">Note un virement ou paiement entre Guillaume et Claire. Ce montant ne compte pas comme une dépense : il vient uniquement réduire le solde dû entre vous.</p><div class="formgrid"><div class="field"><label>Date</label><input id="rdate" type="date" value="${esc(r?.date||new Date().toISOString().slice(0,10))}"></div><div class="field"><label>Qui a envoyé l’argent ?</label><select id="rfrom">${people.map(p=>`<option ${r?.from===p?'selected':''}>${p}</option>`).join('')}</select></div><div class="field"><label>À qui ?</label><select id="rto">${people.map(p=>`<option ${r?.to===p?'selected':''}>${p}</option>`).join('')}</select></div><div class="field"><label>Montant envoyé</label><input id="ramount" type="number" step="0.01" placeholder="0,00" value="${r?Number(r.amount||0):''}"></div><div class="field"><label>Note facultative</label><input id="rnote" placeholder="Ex : virement pour solder les dépenses en retard" value="${esc(r?.note||'')}"></div></div><div class="summaryline" id="rpreview">Le remboursement sera déduit du solde entre vous.</div><div class="actions"><button onclick="saveReimbursement()">${r?'Enregistrer les modifications':'Enregistrer le remboursement'}</button><button class="secondary" onclick="show('home')">Annuler</button></div></div>`); ['rfrom','rto','ramount'].forEach(id=>document.getElementById(id).addEventListener('input',previewReimbursement)); previewReimbursement()}
function previewReimbursement(){const amount=num('ramount'), from=v('rfrom'), to=v('rto'); if(from===to){document.getElementById('rpreview').innerHTML='<b>Choisis deux personnes différentes.</b>';return} document.getElementById('rpreview').innerHTML=amount?`${from} envoie <b>${money(amount)}</b> à ${to}. Ce montant viendra réduire ce que ${from} doit éventuellement à ${to}.`:'Le remboursement sera déduit du solde entre vous.'}
function saveReimbursement(){const amount=num('ramount'), from=v('rfrom'), to=v('rto'); if(!amount){toast('Entre un montant');return} if(from===to){toast('Choisis deux personnes différentes');return} const data={date:v('rdate'),from,to,amount,note:v('rnote')}; if(editingReimbursementId){Object.assign(state.reimbursements.find(r=>r.id===editingReimbursementId),data); toast('Remboursement modifié')} else {state.reimbursements.push({id:uid(),...data}); toast('Remboursement ajouté')} save(); show('home')}
function reimbursementLine(r){return `<div class="item reimbursement"><div class="expense-main"><div class="expense-emoji">💸</div><div><b>Remboursement</b><span>${esc(r.date)} · ${esc(r.from)} → ${esc(r.to)}<br><strong class="redline">${esc(r.from)} a envoyé ${money(r.amount)} à ${esc(r.to)}</strong>${r.note?'<br>'+esc(r.note):''}</span></div></div><div class="rowactions"><div class="amount">${money(r.amount)}</div><button class="small secondary" onclick="editReimbursement('${r.id}')">Modifier</button><button class="small danger" onclick="delReimbursement('${r.id}')">Supprimer</button></div></div>`}
function editReimbursement(id){editingReimbursementId=id; editingId=null; view='reimburse'; render()}
function delReimbursement(id){if(!confirm('Supprimer ce remboursement ?'))return; state.reimbursements=state.reimbursements.filter(r=>r.id!==id); save(); render(); toast('Remboursement supprimé')}


function projectsView(){
  const p=editingProjectId?state.projects.find(x=>x.id===editingProjectId):null;
  layout(`<div class="card"><h2>${p?'Modifier':'Ajouter'} un projet à venir</h2><p class="muted">Cette section sert uniquement à lister les projets prévus. Ils ne modifient pas le solde entre Guillaume et Claire tant qu’ils ne sont pas saisis comme dépenses payées.</p><div class="formgrid"><div class="field"><label>Projet / catégorie</label><select id="pcategory">${categories.map(c=>`<option ${p?.category===c?'selected':''}>${c}</option>`).join('')}</select></div><div class="field"><label>Emoji</label><select id="pemoji">${emojis.map(em=>`<option ${((p?.emoji)||emojiFor(p?.category))===em?'selected':''}>${em}</option>`).join('')}</select></div><div class="field"><label>Nom du projet</label><input id="ptitle" placeholder="Ex : Électricité" value="${esc(p?.title||'')}"></div><div class="field"><label>Montant estimé</label><input id="pamount" type="number" step="0.01" placeholder="0,00" value="${p?Number(p.amount||0):''}"></div></div><div class="field"><label>Remarques</label><textarea id="pnote" placeholder="Ex : devis à demander, prises à déplacer, tableau électrique…">${esc(p?.note||'')}</textarea></div><div class="actions"><button onclick="saveProject()">${p?'Enregistrer les modifications':'Ajouter le projet'}</button>${p?'<button class="secondary" onclick="show(\'projects\')">Annuler</button>':''}<button class="secondary" onclick="show('home')">Retour accueil</button></div></div><section class="card full"><div class="project-total"><div><span class="label">Total projets à venir</span><strong>${money(projectsTotal())}</strong></div><button onclick="editingProjectId=null;render()">+ Nouveau projet</button></div><h3>Liste des projets à venir</h3><div class="list">${state.projects.slice().sort((a,b)=>(a.category||'').localeCompare(b.category||'') || (a.title||'').localeCompare(b.title||'')).map(projectLine).join('')||'<p class="muted">Aucun projet à venir. Ajoute par exemple “Électricité” avec une somme estimée et des remarques.</p>'}</div></section>`);
  document.getElementById('pcategory')?.addEventListener('change',()=>{if(!editingProjectId)document.getElementById('pemoji').value=emojiFor(v('pcategory'))});
}
function projectLine(p){const emo=p.emoji||emojiFor(p.category);return `<div class="item project-line"><div class="expense-main"><div class="expense-emoji">${esc(emo)}</div><div><b>${esc(p.title||p.category||'Projet')}</b><span>${esc(p.category||'')}<br>${p.note?esc(p.note):'Aucune remarque'}</span></div></div><div class="rowactions"><div class="amount">${money(p.amount)}</div><button class="small secondary" onclick="editProject('${p.id}')">Modifier</button><button class="small danger" onclick="delProject('${p.id}')">Supprimer</button></div></div>`}
function saveProject(){const amount=num('pamount'); const data={category:v('pcategory'),emoji:v('pemoji')||emojiFor(v('pcategory')),title:v('ptitle')||v('pcategory'),amount,note:v('pnote')}; if(editingProjectId){Object.assign(state.projects.find(p=>p.id===editingProjectId),data);toast('Projet modifié')}else{state.projects.push({id:uid(),...data});toast('Projet ajouté')} save(); editingProjectId=null; show('projects')}
function editProject(id){editingProjectId=id; view='projects'; render()}
function delProject(id){if(!confirm('Supprimer ce projet à venir ?'))return; state.projects=state.projects.filter(p=>p.id!==id); save(); render(); toast('Projet supprimé')}

const docTypes=['Facture','Devis artisan','Photo','Projection IA','Plan / mesure','Autre'];
function documentsTotalSize(){return state.documents.reduce((s,d)=>s+Number(d.size||0),0)}
function prettySize(bytes){bytes=Number(bytes||0); if(bytes<1024)return bytes+' o'; if(bytes<1024*1024)return (bytes/1024).toFixed(1).replace('.',',')+' Ko'; return (bytes/1024/1024).toFixed(1).replace('.',',')+' Mo'}
function folderName(id){return (state.docFolders.find(f=>f.id===id)||{}).name||'Général'}
function documentsView(){
  const folders=state.docFolders||[];
  const q=(docSearch||'').trim().toLowerCase();
  const activeFolder=currentDocFolder?state.docFolders.find(f=>f.id===currentDocFolder):null;
  const docs=state.documents.slice().filter(d=>{
    const inFolder=!activeFolder || d.folderId===activeFolder.id;
    const text=[d.title,d.name,d.type,d.note,folderName(d.folderId),d.date].join(' ').toLowerCase();
    return inFolder && (!q || text.includes(q));
  }).sort((a,b)=>(b.created||'').localeCompare(a.created||'') || (b.date||'').localeCompare(a.date||''));
  layout(`<div class="grid"><section class="card hero"><h2>Documents</h2><p class="muted">Crée des dossiers, entre dedans et retrouve facilement tes PDF, factures, devis artisans, photos ou projections IA.</p><div class="actions"><button onclick="newFolder()">+ Nouveau dossier</button><button class="secondary" onclick="document.getElementById('docFile').click()">Importer un fichier</button><input id="docFile" type="file" class="hiddenfile" accept="image/*,.pdf,.txt,.json,.doc,.docx,.xls,.xlsx" onchange="prepareDocumentImport(this)"></div></section><div class="card metric documents-card-home"><div class="label">Documents</div><div class="value">${state.documents.length}</div><div class="submetric">${prettySize(documentsTotalSize())} stockés</div></div><div class="card metric documents-card-home"><div class="label">Dossiers</div><div class="value">${folders.length}</div><div class="submetric">clique pour ouvrir</div></div><section class="card full"><div class="documents-toolbar"><div class="field searchfield"><label>Recherche documents</label><input id="docSearch" type="search" placeholder="Rechercher une facture, un devis, une photo…" value="${esc(docSearch)}" oninput="docSearch=this.value;documentsView()"></div>${activeFolder?`<button class="secondary" onclick="currentDocFolder=null;documentsView()">← Tous les dossiers</button>`:''}</div>${activeFolder?`<div class="section-title"><h3>📁 ${esc(activeFolder.name)}</h3><span class="muted">${docs.length} fichier${docs.length>1?'s':''} dans ce dossier</span></div><div class="list">${docs.map(documentLine).join('')||'<p class="muted">Aucun fichier dans ce dossier.</p>'}</div>`:`<div class="section-title"><h3>Dossiers</h3><span class="muted">Clique sur un dossier pour voir les fichiers qu’il contient.</span></div><div class="foldergrid">${folders.map(folderCard).join('')}</div>${q?`<div class="section-title search-results-title"><h3>Résultats de recherche</h3><span class="muted">${docs.length} fichier${docs.length>1?'s':''} trouvé${docs.length>1?'s':''}</span></div><div class="list">${docs.map(documentLine).join('')||'<p class="muted">Aucun document trouvé.</p>'}</div>`:''}`}</section></div>`)
}
function folderCard(f){const count=state.documents.filter(d=>d.folderId===f.id).length;return `<div class="foldercard folder-open" onclick="openFolder('${f.id}')"><div class="foldericon">📁</div><div><b>${esc(f.name)}</b><span>${count} fichier${count>1?'s':''}</span></div><div class="rowactions"><button class="small secondary" onclick="event.stopPropagation();renameFolder('${f.id}')">Renommer</button>${f.id==='general'?'':`<button class="small danger" onclick="event.stopPropagation();deleteFolder('${f.id}')">Supprimer</button>`}</div></div>`}
function openFolder(id){currentDocFolder=id;documentsView()}
function newFolder(){const name=prompt('Nom du nouveau dossier ?'); if(!name)return; state.docFolders.push({id:uid(),name:name.trim()}); save(); render(); toast('Dossier créé')}
function renameFolder(id){const f=state.docFolders.find(x=>x.id===id); if(!f)return; const name=prompt('Nouveau nom du dossier',f.name); if(!name)return; f.name=name.trim(); save(); render(); toast('Dossier modifié')}
function deleteFolder(id){if(!confirm('Supprimer ce dossier ? Les fichiers seront déplacés dans Général.'))return; state.documents.forEach(d=>{if(d.folderId===id)d.folderId='general'}); state.docFolders=state.docFolders.filter(f=>f.id!==id); if(currentDocFolder===id)currentDocFolder=null; save(); render(); toast('Dossier supprimé')}
function prepareDocumentImport(input){const file=input.files&&input.files[0]; if(!file)return; const max=4.5*1024*1024; if(file.size>max){toast('Fichier trop lourd : max 4,5 Mo'); input.value=''; return} const reader=new FileReader(); reader.onload=()=>showDocumentImportForm(file,reader.result); reader.readAsDataURL(file)}
function showDocumentImportForm(file,dataUrl){const folders=state.docFolders||[{id:'general',name:'Général'}]; layout(`<div class="card"><h2>Importer un document</h2><p class="muted">Choisis le dossier et la nature du fichier avant de l’ajouter.</p><div class="import-preview"><div class="filebig">${file.type.startsWith('image/')?'🖼️':'📄'}</div><div><b>${esc(file.name)}</b><span>${esc(file.type||'fichier')} · ${prettySize(file.size)}</span></div></div><div class="formgrid"><div class="field"><label>Dossier</label><select id="docFolder">${folders.map(f=>`<option value="${f.id}">${esc(f.name)}</option>`).join('')}</select></div><div class="field"><label>Nature du fichier</label><select id="docType">${docTypes.map(t=>`<option>${t}</option>`).join('')}</select></div><div class="field"><label>Nom affiché</label><input id="docTitle" value="${esc(file.name)}"></div><div class="field"><label>Date</label><input id="docDate" type="date" value="${new Date().toISOString().slice(0,10)}"></div></div><div class="field"><label>Remarques</label><textarea id="docNote" placeholder="Ex : facture carrelage, devis électricité, projection cuisine…"></textarea></div><div class="actions"><button onclick="saveDocumentFromImport('${esc(dataUrl)}', '${esc(file.name)}', '${esc(file.type)}', ${Number(file.size)})">Ajouter le document</button><button class="secondary" onclick="show('documents')">Annuler</button></div></div>`)}
async function saveDocumentFromImport(dataUrl,name,mime,size){const folderId=v('docFolder')||'general'; const doc={id:uid(),folderId,type:v('docType')||'Autre',title:v('docTitle')||name,date:v('docDate'),note:v('docNote'),name,mime,size,dataUrl,created:new Date().toISOString()}; state.documents.push(doc); currentDocFolder=folderId; show('documents'); toast('Envoi du document…'); try{if(cloudSession) await uploadDocument(doc); save(); toast('Document ajouté et synchronisé')}catch(e){console.error(e);save();toast('Document ajouté localement — envoi cloud à réessayer')}}
function documentLine(d){return `<div class="item document-line"><div class="expense-main"><div class="expense-emoji">${(d.mime||'').startsWith('image/')?'🖼️':'📄'}</div><div><b>${esc(d.title||d.name)}</b><span>${esc(d.date||'')} · ${esc(folderName(d.folderId))} · ${esc(d.type||'Autre')} · ${prettySize(d.size)}${d.note?'<br>'+esc(d.note):''}</span></div></div><div class="rowactions"><button class="small secondary" onclick="openDocument('${d.id}')">Ouvrir</button><button class="small secondary" onclick="editDocument('${d.id}')">Modifier</button><button class="small danger" onclick="deleteDocument('${d.id}')">Supprimer</button></div></div>`}
async function openDocument(id){const d=state.documents.find(x=>x.id===id); if(!d)return; let url=d.dataUrl; try{if(d.storagePath&&cloudSession) url=await signedDocumentUrl(d.storagePath)}catch(e){console.error(e)} if(!url){toast('Document indisponible');return} window.open(url,'_blank')}
function editDocument(id){const d=state.documents.find(x=>x.id===id); if(!d)return; layout(`<div class="card"><h2>Modifier le document</h2><div class="formgrid"><div class="field"><label>Dossier</label><select id="docFolder">${state.docFolders.map(f=>`<option value="${f.id}" ${d.folderId===f.id?'selected':''}>${esc(f.name)}</option>`).join('')}</select></div><div class="field"><label>Nature du fichier</label><select id="docType">${docTypes.map(t=>`<option ${d.type===t?'selected':''}>${t}</option>`).join('')}</select></div><div class="field"><label>Nom affiché</label><input id="docTitle" value="${esc(d.title||'')}"></div><div class="field"><label>Date</label><input id="docDate" type="date" value="${esc(d.date||'')}"></div></div><div class="field"><label>Remarques</label><textarea id="docNote">${esc(d.note||'')}</textarea></div><div class="actions"><button onclick="saveDocumentEdit('${d.id}')">Enregistrer</button><button class="secondary" onclick="show('documents')">Annuler</button></div></div>`)}
function saveDocumentEdit(id){const d=state.documents.find(x=>x.id===id); if(!d)return; Object.assign(d,{folderId:v('docFolder'),type:v('docType'),title:v('docTitle'),date:v('docDate'),note:v('docNote')}); save(); show('documents'); toast('Document modifié')}
async function deleteDocument(id){if(!confirm('Supprimer ce document ?'))return; const d=state.documents.find(x=>x.id===id); if(d&&d.storagePath&&cloudSession){try{await deleteStoredDocument(d.storagePath)}catch(e){console.error(e)}} state.documents=state.documents.filter(d=>d.id!==id); save(); render(); toast('Document supprimé')}

function historyView(){layout(`<div class="card"><h2>Historique</h2><p class="muted">Toutes les dépenses et remboursements enregistrés.</p><div class="actions"><button onclick="exportData()">Exporter</button><button class="secondary" onclick="importData()">Importer</button></div><h3>Dépenses</h3><div class="list" style="margin-top:14px">${state.expenses.slice().sort((a,b)=>(b.date||'').localeCompare(a.date||'') || String(b.id).localeCompare(String(a.id))).map(expenseLine).join('')||'<p class="muted">Aucune dépense.</p>'}</div><h3>Remboursements</h3><div class="list" style="margin-top:14px">${state.reimbursements.slice().sort((a,b)=>(b.date||'').localeCompare(a.date||'') || String(b.id).localeCompare(String(a.id))).map(reimbursementLine).join('')||'<p class="muted">Aucun remboursement.</p>'}</div></div>`) }
function edit(id){editingId=id; view='add'; render()}
function del(id){if(!confirm('Supprimer cette dépense ?'))return; state.expenses=state.expenses.filter(e=>e.id!==id); save(); render(); toast('Dépense supprimée')}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='maison-50-50-depenses.json'; a.click(); URL.revokeObjectURL(a.href)}
function importData(){const inp=document.createElement('input'); inp.type='file'; inp.accept='application/json'; inp.onchange=async()=>{try{const data=JSON.parse(await inp.files[0].text()); if(!data.expenses)throw new Error(); state={expenses:data.expenses||[],reimbursements:data.reimbursements||[],projects:data.projects||[],docFolders:data.docFolders||[{id:'general',name:'Général'}],documents:data.documents||[]}; save(); render(); toast('Import réussi')}catch(e){toast('Fichier invalide')}}; inp.click()}
function resetAll(){if(confirm('Effacer toutes les dépenses et remboursements ?')){state={expenses:[],reimbursements:[],projects:[],docFolders:[{id:'general',name:'Général'}],documents:[]}; save(); render(); toast('Données effacées')}}
// --- Synchronisation Supabase ---
const SUPABASE_URL='https://vcdztuiwethnqdubqbkf.supabase.co';
const SUPABASE_KEY='sb_publishable_rcdRN1EIjIpLR0TEZ5kW9g_uWYpdGW3';
const SESSION_KEY='maison5050_supabase_session';
let cloudSession=null, syncTimer=null;
let syncState='idle', lastSyncAt=null, syncBusy=0;
function syncLabel(){
  if(!navigator.onLine)return '⚠️ Hors ligne';
  if(syncState==='syncing')return '↻ Synchronisation…';
  if(syncState==='error')return '⚠️ Erreur de synchro';
  if(lastSyncAt)return '☁️ Synchronisé · '+lastSyncAt.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'});
  return '☁️ Connecté';
}
function updateSyncIndicator(){const el=document.getElementById('syncIndicator');if(!el)return;el.textContent=syncLabel();el.dataset.state=!navigator.onLine?'offline':syncState;}
function beginSync(){syncBusy++;syncState='syncing';updateSyncIndicator()}
function endSync(ok=true){syncBusy=Math.max(0,syncBusy-1);if(syncBusy===0){syncState=ok?'ok':'error';if(ok)lastSyncAt=new Date();updateSyncIndicator()}}
function ensureSyncIndicator(){const top=document.querySelector('.top');if(!top)return;let el=document.getElementById('syncIndicator');if(!el){el=document.createElement('div');el.id='syncIndicator';el.className='sync-indicator';el.setAttribute('aria-live','polite');top.appendChild(el)}updateSyncIndicator()}

function apiHeaders(extra={}){return {'apikey':SUPABASE_KEY,'Authorization':'Bearer '+cloudSession.access_token,...extra}}
function loginView(message=''){
  document.querySelector('.bottom').style.display='none';document.querySelector('.topnav').style.display='none';
  layout(`<div class="card login-card"><h2>🏠 La maison des mimis</h2><p class="muted">Connecte-toi pour retrouver les mêmes données sur Mac et iPhone.</p>${message?`<p class="sync-error">${esc(message)}</p>`:''}<div class="field"><label>E-mail</label><input id="loginEmail" type="email" autocomplete="username"></div><div class="field"><label>Mot de passe</label><input id="loginPassword" type="password" autocomplete="current-password" onkeydown="if(event.key==='Enter')login()"></div><div class="actions"><button onclick="login()">Se connecter</button></div></div>`)
}
async function login(){
  const email=v('loginEmail'),password=v('loginPassword'); if(!email||!password){toast('Entre ton e-mail et ton mot de passe');return}
  try{const r=await fetch(SUPABASE_URL+'/auth/v1/token?grant_type=password',{method:'POST',headers:{'apikey':SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})}); const j=await r.json(); if(!r.ok)throw new Error(j.error_description||j.msg||'Connexion impossible'); cloudSession=j; localStorage.setItem(SESSION_KEY,JSON.stringify(j)); await startCloud() }catch(e){loginView(e.message)}
}
async function logout(){localStorage.removeItem(SESSION_KEY);cloudSession=null;clearInterval(syncTimer);loginView('Déconnecté.')}
async function refreshSession(){
  if(!cloudSession?.refresh_token)return false;
  const r=await fetch(SUPABASE_URL+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{'apikey':SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:cloudSession.refresh_token})});
  if(!r.ok)return false; cloudSession=await r.json();localStorage.setItem(SESSION_KEY,JSON.stringify(cloudSession));return true
}
function cloudState(){return {...state,documents:(state.documents||[]).map(({dataUrl,...d})=>d)}}
async function cloudFetch(){
  beginSync();
  try{
    let r=await fetch(SUPABASE_URL+'/rest/v1/app_data?id=eq.maison-50-50&select=data,updated_at',{headers:apiHeaders()});
    if(r.status===401&&await refreshSession())r=await fetch(SUPABASE_URL+'/rest/v1/app_data?id=eq.maison-50-50&select=data,updated_at',{headers:apiHeaders()});
    if(!r.ok)throw new Error('Lecture cloud impossible'); const rows=await r.json(); endSync(true); return rows[0]?.data||{}
  }catch(e){endSync(false);throw e}
}
async function cloudSave(){
  beginSync();
  try{
    const body={data:cloudState(),updated_at:new Date().toISOString()}; let r=await fetch(SUPABASE_URL+'/rest/v1/app_data?id=eq.maison-50-50',{method:'PATCH',headers:apiHeaders({'Content-Type':'application/json','Prefer':'return=minimal'}),body:JSON.stringify(body)});
    if(r.status===401&&await refreshSession())r=await fetch(SUPABASE_URL+'/rest/v1/app_data?id=eq.maison-50-50',{method:'PATCH',headers:apiHeaders({'Content-Type':'application/json','Prefer':'return=minimal'}),body:JSON.stringify(body)}); if(!r.ok)throw new Error('Sauvegarde cloud impossible'); endSync(true)
  }catch(e){endSync(false);throw e}
}
function dataUrlToBlob(dataUrl){const [h,b]=dataUrl.split(',');const mime=(h.match(/data:(.*?);/)||[])[1]||'application/octet-stream';const bin=atob(b),a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);return new Blob([a],{type:mime})}
async function uploadDocument(d){if(!d.dataUrl||d.storagePath)return; const safe=(d.name||'document').replace(/[^a-zA-Z0-9._-]/g,'_'); const path=d.id+'-'+safe; const r=await fetch(SUPABASE_URL+'/storage/v1/object/maison-documents/'+encodeURIComponent(path),{method:'POST',headers:apiHeaders({'Content-Type':d.mime||'application/octet-stream','x-upsert':'true'}),body:dataUrlToBlob(d.dataUrl)}); if(!r.ok)throw new Error('Envoi document impossible'); d.storagePath=path; delete d.dataUrl}
async function signedDocumentUrl(path){const r=await fetch(SUPABASE_URL+'/storage/v1/object/sign/maison-documents/'+encodeURIComponent(path),{method:'POST',headers:apiHeaders({'Content-Type':'application/json'}),body:JSON.stringify({expiresIn:3600})});const j=await r.json();if(!r.ok)throw new Error('Ouverture impossible');return SUPABASE_URL+'/storage/v1'+j.signedURL}
async function deleteStoredDocument(path){const r=await fetch(SUPABASE_URL+'/storage/v1/object/maison-documents/'+encodeURIComponent(path),{method:'DELETE',headers:apiHeaders()});if(!r.ok)throw new Error('Suppression cloud impossible')}
async function migrateLocalDocuments(){for(const d of state.documents||[]){if(d.dataUrl&&!d.storagePath){try{await uploadDocument(d)}catch(e){console.error(e)}}}}
async function pullCloud(){try{const c=await cloudFetch(); if(c&&Object.keys(c).length){state={expenses:c.expenses||[],reimbursements:c.reimbursements||[],projects:c.projects||[],docFolders:c.docFolders||[{id:'general',name:'Général'}],documents:c.documents||[]};localStorage.setItem(KEY,JSON.stringify(state));render()}}catch(e){console.error(e)}}
async function startCloud(){
  document.querySelector('.bottom').style.display='flex';document.querySelector('.topnav').style.display='flex';
  try{const cloud=await cloudFetch(); const local=load(); const cloudEmpty=!(cloud.expenses?.length||cloud.reimbursements?.length||cloud.projects?.length||cloud.documents?.length);
    if(cloudEmpty&&(local.expenses.length||local.reimbursements.length||local.projects.length||local.documents.length)){state=local;await migrateLocalDocuments();await cloudSave();toast('Données locales envoyées dans le cloud')}
    else if(Object.keys(cloud).length){state={expenses:cloud.expenses||[],reimbursements:cloud.reimbursements||[],projects:cloud.projects||[],docFolders:cloud.docFolders||[{id:'general',name:'Général'}],documents:cloud.documents||[]};localStorage.setItem(KEY,JSON.stringify(state))}
    render(); addCloudButton(); ensureSyncIndicator(); clearInterval(syncTimer);syncTimer=setInterval(pullCloud,15000)
  }catch(e){loginView('Connexion au cloud impossible. Vérifie la connexion internet.')}
}
function addCloudButton(){const top=document.querySelector('.top');if(!top)return;let actions=top.querySelector('.top-actions');if(!actions){actions=document.createElement('div');actions.className='top-actions';const reset=top.querySelector('button.secondary');if(reset){reset.classList.add('reset-btn');actions.appendChild(reset)}top.appendChild(actions)}if(!document.getElementById('themeToggle')){const t=document.createElement('button');t.id='themeToggle';t.className='secondary theme-toggle';t.onclick=toggleTheme;actions.appendChild(t)}if(!document.getElementById('cloudLogout')){const b=document.createElement('button');b.id='cloudLogout';b.className='secondary';b.textContent='Déconnexion';b.onclick=logout;actions.appendChild(b)}applyTheme();ensureSyncIndicator()}
async function boot(){try{cloudSession=JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch(e){} if(cloudSession){await startCloud()}else loginView()}
window.addEventListener('focus',()=>{if(cloudSession)pullCloud()});
window.addEventListener('online',()=>{updateSyncIndicator();if(cloudSession)pullCloud()});
window.addEventListener('offline',updateSyncIndicator);
boot();
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{})}
